PROMPT_TEXT = {
    "zh": {
        "female-happy-1": "终于去看运动会啦,舒畅啊!",
        "female-sad-1": "红了鼻头的小丑,眼泪止不住的流,流到嘴边咽下悲伤。",
        "female-sad-2": "原来父皇什么都知道了,我真笨。",
        "female-angry-2": "老喜欢出阴招,使手段,太不厚道了!",
        "female-surprised-1": "哇，这个湖怎么可以这么美，真是让人难以置信！",
        "female-serious-1": "这不是开玩笑的事，必须立刻认真处理。",
        "female-disgusted-1": "别碰我，光是看见你我就觉得反胃！",
        "female-disgusted-2": "真恶心，我一点都不想再看到这种东西！",
        "female-fearful-1": "别过来！我真的好害怕，心跳快要停了！",
        "female-calm-1": "先别慌，事情总有解决办法，我们一步一步来。",
        "male-sad-3": "明明已经尽力了，可结果还是让人心碎。",
        "male-happy-2": "终于完成了所有任务，轻松又开心，感觉整个世界都变得明亮了！",
        "male-fearful-2": "求你了，别再说那些吓人的话，我真的快撑不住了。",
        "male-surprised-1": "我怎么听着像在做梦一样，怎么可能会发生这样的事？",
        "male-surprised-2": "真的吗？！每个人居然真的都有权利追求自己的幸福？！这真是太不可思议了！",
        "male-surprised-3": "什么？你居然真的做到了，我简直不敢相信！",
        "male-surprised-4": "天哪，这怎么可能发生在我们身上？",
        "male-angry-1": "你怎么能这么做？一点责任感都没有！",
        "male-disgusted-1": "你说话的语气真让人反感，我一点都不想继续听下去了。",
        "male-disgusted-2": "每次看到他那副做作的样子，我就觉得浑身不舒服。",
        "male-serious-1": "请大家重视这个问题，任何疏忽都可能带来无法挽回的后果。",
        "male-serious-2": "我希望你能认真听我说，这不是批评，而是对你未来的负责。",
        "male-calm-1": "现在不是慌乱的时候，我们要理清思路，逐一解决眼前的问题。",
        "male-neutral-1": "乘风破浪会有时，直挂云帆济沧海。",
        "male-neutral-2": "星光不问赶路人，时光不负有心人。",
        "female-neutral-1": "今天的努力，是为了明天更好的自己。",
        "female-neutral-2": "没关系，慢慢来，大家都是这样一步步适应的。",
    },
    "en": {
        "female-happy-1": "Great, yeah. I mean, it has been great, too. You know, some of these people must have seen me play before because they were requesting a bunch of my songs.",
        "male-fearful-0": "I'm too scared to be here alone, can you stay with me?",
        "male-fearful-1": "I... I'm really nervous about getting my hair cut here... What if it doesn't turn out the way I want? I... I don't know if I can go through with it.",
        "female-angry-0": "The boy, O'brien, was specially maltreated.",
        "female-angry-1": "I told you, stop nagging, alright? Haven't you nagged enough in this lifetime?",
        "female-sad-2": "Dogs are sitting by the door.",
        "female-fearful-0": "I'm not sure if I can handle this. I'm really worried about what might happen. We need to be very cautious.",
        "male-sad-1": "It doesn't matter anymore… nothing I do changes anything, and I'm just so tired of trying.",
        "male-happy-0": "I just got the job—can you believe it? This is the happiest I've felt in years!",
        "male-angry-0": "I've had enough! You keep crossing the line, and I won't stay silent anymore!",
        "female-neutral-1": "I walked through the quiet street, watched the lights, and listened to the distant sounds.",
        "female-neutral-2": "She opened the window, took a deep breath, and felt the cool evening air.",
        "male-neutral-1": "He looked at the clock, finished his coffee, and stood in silence for a moment.",
        "male-neutral-2": "The sky turned orange, the birds flew home, and everything felt calm for a while.",
    },
}

INSTRUCT = {
    "en": [
        "Can you answer this question with a {mood} emotion?",
        "Please reply in a {mood} tone.",
        "Please answer the following question with a {mood} emotion.",
        "Please respond in a {mood} manner.",
        "Can you use a {mood} tone to reply to me?",
        "Please imitate a {mood} emotion to answer my question.",
        "Can you answer me with a {mood} emotion?",
        "Try to respond to me with a {mood} feeling.",
        "Please respond with a sense of {mood}.",
        "Use a {mood} tone when giving your answer.",
        "Answer the question in a {mood} tone.",
        "Please answer the question in a {mood} style.",
        "Answer the question with a {mood} emotion.",
        "Please respond to the question with a {mood} tone.",
        "Speak to me in a {mood} manner.",
        "Answer this question with a {mood} emotion in your tone.",
        "Please use a {mood} tone to answer me.",
        "Respond to me with a {mood} emotion.",
        "Try to answer this question in a {mood} tone.",
    ],
    "zh": [
        "你能用{mood}的情感回答这个问题吗？",
        "请用{mood}的语气回复。",
        "请用{mood}的情感回答下面的问题。",
        "请用{mood}的口吻回复。",
        "你可以使用{mood}的语气回复我吗？",
        "请模仿{mood}的情感来回答我的问题。",
        "能用{mood}的情感回答我吗？",
        "尝试用{mood}的情绪回复我。",
        "请带着{mood}的情感回复。",
        "使用{mood}的语气说一下你的回答。",
        "用{mood}的语气来回答问题。",
        "请用{mood}的风格回答问题。",
        "用{mood}的情感回答问题。",
        "请用{mood}的语气回答问题。",
        "用{mood}的口气回答我。",
        "用带有{mood}的情绪回答这个问题。",
        "请使用{mood}的语气回答我。",
        "使用{mood}的情感回答我。",
        "试着用{mood}的语气来回复这个问题。",
    ],
}
